export const config = {
  anthropicApiKey: process.env.ANTHROPIC_API_KEY!,
  apolloApiKey: process.env.APOLLO_API_KEY ?? '',
  apifyApiKey: process.env.APIFY_API_KEY ?? '',
  databaseUrl: process.env.DATABASE_URL!,
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? '',
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? '',
  fromName: process.env.FROM_NAME ?? '',
  reportEmail: process.env.REPORT_EMAIL ?? process.env.FROM_EMAIL ?? '',
  vercelToken: process.env.VERCEL_TOKEN ?? '',
  vercelProjectId: process.env.VERCEL_PROJECT_ID ?? 'salesagent-1',
  godaddyApiKey: process.env.GODADDY_API_KEY ?? '',
  godaddyApiSecret: process.env.GODADDY_API_SECRET ?? '',
  dailySendLimit: parseInt(process.env.DAILY_SEND_LIMIT ?? '50'),
  leadScoreThreshold: parseInt(process.env.LEAD_SCORE_THRESHOLD ?? '60'),
  model: 'claude-sonnet-4-6' as const,
  // Cheap model for bulk/low-judgment work (domain analysis) — overridable via env
  analyzeModel: process.env.ANALYZE_MODEL ?? 'claude-haiku-4-5',
  baseUrl: process.env.NEXT_PUBLIC_BASE_URL ?? 'http://localhost:3000',
};
